### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by adminlinzi** [UltimateHackers/Hash-Buster#7]
root@kali:/opt/Hash-Buster# python hash.py 
--------------------------------------------------------
	     Made with <3 By Team Ultimate
_  _ ____ ____ _  _    ___  _  _ ____ ___ ____ ____ 
|__| |__| [__  |__|    |__] |  | [__   |  |___ |__/ 
|  | |  | ___] |  |    |__] |__| ___]  |  |___ |  \  v1.0
Servers Loaded: Alpha, Beta, Gamma, Delta, Omega, Lambda
--------------------------------------------------------
Enter your hash: 75628e11559b43febdffd113007f76ad
[!] Hash function : MD5
Traceback (most recent call last):
  File "hash.py", line 63, in <module>
    purl = urlopen(url).read()
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 111] Connection refused
root@kali:/opt/Hash-Buster# 

#################################################################
password is qwe@123456  
md5 is 75628e11559b43febdffd113007f76ad

**Comment by UltimateHackers** [comment]
Looks like the server was down at that time so the connection timed out. Thanks for reporting, I will make Hash Buster handle such errors.
